/**
 * Copyright (C) 2012 Ovidiu-Laurian Ionescu
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

package net.ionescu.jhocr2pdf;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.xml.sax.Attributes;
import org.xml.sax.ContentHandler;
import org.xml.sax.ErrorHandler;
import org.xml.sax.InputSource;
import org.xml.sax.Locator;
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;
import org.xml.sax.XMLReader;
import org.xml.sax.helpers.XMLReaderFactory;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;

/**
 * Combines a PDF file containing scanned TIFF images with the OCR generated by Tesseract
 * @author Ovidiu Ionescu
 *
 */
public class Jhocr2pdf implements ContentHandler, ErrorHandler {

	PdfStamper stamper;
	PdfContentByte canvas;
	BaseFont bf;
	float xScaling;
	float yScaling;
	
	boolean visible;
	
	
	StringBuilder text = new StringBuilder();
	String coords;
	@Override
	public void setDocumentLocator(Locator locator) {
		
	}

	@Override
	public void startDocument() throws SAXException {
		
	}

	@Override
	public void endDocument() throws SAXException {
		
	}

	@Override
	public void startPrefixMapping(String prefix, String uri)
			throws SAXException {
		
	}

	@Override
	public void endPrefixMapping(String prefix) throws SAXException {
		
	}

	@Override
	public void startElement(String uri, String localName, String qName,
			Attributes atts) throws SAXException {
		text.setLength(0);
		coords = null;
		
		// test if we encountered an OCR word
		if(localName.equals("span")) {
			String klass = atts.getValue("class");
			if(null != klass && klass.equals("ocr_word")) {
				coords = atts.getValue("title");
			}
		}
		
		// test if we encountered start of page
		if(localName.equals("div")) {
			String klass = atts.getValue("class");
			if(null != klass && klass.equals("ocr_page")) {
				// Load the corresponding page of the PDF file
				String id = atts.getValue("id");
				int pageNum = Integer.valueOf(id.split("_")[1], 10);
				if(visible) {
					canvas = stamper.getOverContent(pageNum);
				} else {
					canvas = stamper.getUnderContent(pageNum);
				}
				
				// Calculate the scaling of the image
				String title[] = atts.getValue("title").split(" ");
				float imgWidth = Float.valueOf(title[title.length - 2]) - Float.valueOf(title[title.length - 4]);
				float imgHeight = Float.valueOf(title[title.length - 1]) - Float.valueOf(title[title.length - 3]);
				xScaling = PageSize.A4.getWidth() / imgWidth;
				yScaling = PageSize.A4.getHeight() / imgHeight;
//				System.out.println("Load page " + pageNum + " with scaling " + xScaling + "x" + yScaling);
			}
		}
	}

	@Override
	public void endElement(String uri, String localName, String qName)
			throws SAXException {
		if(coords != null && text.length() > 0) {
//			System.out.println(coords + " " + text);
			addSpan(coords, text.toString());
		}
		coords = null;
	}

	@Override
	public void characters(char[] ch, int start, int length)
			throws SAXException {
		text.append(ch, start, length);
	}

	@Override
	public void ignorableWhitespace(char[] ch, int start, int length)
			throws SAXException {
		
	}

	@Override
	public void processingInstruction(String target, String data)
			throws SAXException {
		
	}

	@Override
	public void skippedEntity(String name) throws SAXException {
		
	}

	@Override
	public void warning(SAXParseException exception) throws SAXException {
		
	}

	@Override
	public void error(SAXParseException exception) throws SAXException {
		
	}

	@Override
	public void fatalError(SAXParseException exception) throws SAXException {
		
	}
	
	public void addSpan(String coords, String text) {
		// parse the coordinates
		String[] coord = coords.split(" ");
		Rectangle rect = new Rectangle(
				Float.valueOf(coord[1]), 
				Float.valueOf(coord[4]),
				Float.valueOf(coord[3]),
				Float.valueOf(coord[2]));
		
		canvas.saveState();
		canvas.beginText();
		canvas.setTextRenderingMode(PdfContentByte.TEXT_RENDER_MODE_FILL);
		canvas.setRGBColorFill(0xFF, 0, 0);
		canvas.setLineWidth(0);
		
		// calculate the font size
		float width = rect.getWidth() * xScaling;
		
		float tenWidth = bf.getWidthPointKerned(text, 10);
                float fontSize = 10 * width / tenWidth;
		
		canvas.setFontAndSize(bf, fontSize);
		canvas.showTextAlignedKerned(
				Element.ALIGN_LEFT, 
				text, 
				rect.getLeft() * xScaling, 
				PageSize.A4.getHeight() - rect.getBottom() * yScaling - bf.getDescentPoint(text, fontSize), 
				0);
		canvas.endText();
		canvas.restoreState();
		
	}
	
	
	@SuppressWarnings("unused")
	private  Jhocr2pdf() {
		
	}
	
	public Jhocr2pdf(PdfStamper stamper, boolean visible, String fontPath) throws DocumentException, IOException {
		this.stamper = stamper;
		this.visible = visible;
		if(fontPath != null) {
			bf = BaseFont.createFont(fontPath, BaseFont.WINANSI, BaseFont.EMBEDDED);
		} else {
			bf = BaseFont.createFont();
		}
	}
	
	public void parse(String fileName) throws SAXException, IOException {
		XMLReader reader;
		reader = XMLReaderFactory.createXMLReader();
		reader.setContentHandler(this);
		reader.setErrorHandler(this);
		
		final BufferedReader characterStream = new BufferedReader(new InputStreamReader(new FileInputStream(fileName), "UTF8"));
		// skip past the DOCTYPE line
		characterStream.readLine();
		
		Reader filter = new Reader() {

			@Override
			public int read(char[] cbuf, int off, int len) throws IOException {
				int chars = characterStream.read(cbuf, off, len);
				//  filter out all non XML characters
				for(int i = 0; i < chars; i++) {
					int c = cbuf[i + off];
					if(c == 0x0009 || c == 0x000A || c == 0x000D
							|| (c >= 0x0020 && c <= 0xD7FF) 
							|| (0x10000 <= c && c <= 0x10FFFF)) {
								// c is XML valid, leave it alone
							} else {
								cbuf[i + off] = ' ';									
							}
				}	
				return chars;
			}

			@Override
			public void close() throws IOException {
				characterStream.close();
				
			}
			
		};
		reader.parse(new InputSource(filter));
	}
	
	/**
	 * @param args
	 * The arguments are:
	 *  PDF file containing the TIFF images
	 *  hOCR file generated by Tesseract
	 *  Output PDF file with the added OCR information
	 * flags:
	 *   -visible :render the text above the image
         *   -font font_path  :path to the font file to use
         *
	 * Usage example:
         * java -jar jhorc2pdf.jar -font /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf input.pdf input.html output.pdf
         *
	 * @throws SAXException
	 * @throws IOException
	 * @throws DocumentException
	 */
	public static void main(String[] args) throws SAXException, IOException, DocumentException {
		/*
		 * process input parameters
		 * 
		 * -visible -font font_path inputPDF inputOCR outputPDF
		 */
		boolean visible = false;
		String fontPath = null;
		List<String>paths = new ArrayList<String>();
		
		for(int i = 0; i < args.length; i++) {
			if(args[i].startsWith("-")) {
				if(args[i].equals("-visible")) {
					visible = true;
					continue;
				}
				if(args[i].equals("-font")) {
					i++;
					fontPath = args[i];
					continue;
				}
				System.err.println("Invalid parameter: " + args[i]);
				System.exit(1);
			} else {
				paths.add(args[i]);
			}
		}
		
		// load the PDF file, initialize the Stamper
		PdfReader reader = new PdfReader(paths.get(0));
		PdfStamper stamper = new PdfStamper(reader, new FileOutputStream(paths.get(2)));
		
		Map<String, String> info = reader.getInfo();
		info.put("Title", new File(paths.get(2)).getName());
		stamper.setMoreInfo(info);

		Jhocr2pdf ocrStamp = new Jhocr2pdf(stamper, visible, fontPath);
		ocrStamp.parse(paths.get(1));
		stamper.close();
	}
}
